(define freetileprefix "cd ~/repos/freetile;python -m freetile ")

(xbindkey '(mod4 "space") (string-append freetileprefix "tile"))

(xbindkey '(mod4 "h")  (string-append freetileprefix "focus left"))
(xbindkey '(mod4 "j")  (string-append freetileprefix "focus down"))
(xbindkey '(mod4 "k")  (string-append freetileprefix "focus up  "))
(xbindkey '(mod4 "l")  (string-append freetileprefix "focus right"))
(xbindkey '(mod4 shift "h") (string-append freetileprefix "swap left")) 
(xbindkey '(mod4 shift "j") (string-append freetileprefix "swap down")) 
(xbindkey '(mod4 shift "k") (string-append freetileprefix "swap up  ")) 
(xbindkey '(mod4 shift "l") (string-append freetileprefix "swap right"))
(xbindkey '(mod4 shift control "h") (string-append freetileprefix "shrink width"))
(xbindkey '(mod4 shift control "j") (string-append freetileprefix "grow height"))
(xbindkey '(mod4 shift control "k") (string-append freetileprefix "shrink height"))
(xbindkey '(mod4 shift control "l") (string-append freetileprefix "grow width"))
(xbindkey '(mod4 control "h") (string-append freetileprefix "move left"))
(xbindkey '(mod4 control "j") (string-append freetileprefix "move down"))
(xbindkey '(mod4 control "k") (string-append freetileprefix "move up  "))
(xbindkey '(mod4 control "l") (string-append freetileprefix "move right"))
