(xbindkey '(mod4 "space") "bash bin/tile tile")

(xbindkey '(mod4 "h") "bash bin/tile focus left")
(xbindkey '(mod4 "j") "bash bin/tile focus down")
(xbindkey '(mod4 "k") "bash bin/tile focus up  ")
(xbindkey '(mod4 "l") "bash bin/tile focus right")
(xbindkey '(mod4 shift "h") "bash bin/tile swap left")
(xbindkey '(mod4 shift "j") "bash bin/tile swap down")
(xbindkey '(mod4 shift "k") "bash bin/tile swap up  ")
(xbindkey '(mod4 shift "l") "bash bin/tile swap right")
(xbindkey '(mod4 shift control "h") "bash bin/tile shrink width")
(xbindkey '(mod4 shift control "j") "bash bin/tile grow height")
(xbindkey '(mod4 shift control "k") "bash bin/tile shrink height")
(xbindkey '(mod4 shift control "l") "bash bin/tile grow width")
(xbindkey '(mod4 control "h") "bash bin/tile move left")
(xbindkey '(mod4 control "j") "bash bin/tile move down")
(xbindkey '(mod4 control "k") "bash bin/tile move up  ")
(xbindkey '(mod4 control "l") "bash bin/tile move right")
