#!/bin/sh


KDE_FULL_SESSION=true
export KDE_FULL_SESSION
xprop -root -f KDE_FULL_SESSION 8t -set KDE_FULL_SESSION true

KDE_SESSION_VERSION=5
export KDE_SESSION_VERSION
xprop -root -f KDE_SESSION_VERSION 32c -set KDE_SESSION_VERSION 5

KDE_SESSION_UID=`id -ru`
export KDE_SESSION_UID

XDG_CURRENT_DESKTOP=KDE
export XDG_CURRENT_DESKTOP

# At this point all environment variables are set, let's send it to the DBus session server to update the activation environment
#if which dbus-update-activation-environment >/dev/null 2>/dev/null ; then
    dbus-update-activation-environment --systemd --all
#else
#    /usr/lib/ksyncdbusenv
#fi
#if test $? -ne 0; then
#  # Startup error
#  echo 'startkde: Could not sync environment to dbus.'  1>&2
#  test -n "$ksplash_pid" && kill "$ksplash_pid" 2>/dev/null
#  xmessage -geometry 500x100 "Could not sync environment to dbus."
#  exit 1
#fi

# We set LD_BIND_NOW to increase the efficiency of kdeinit.
# kdeinit unsets this variable before loading applications.
#LD_BIND_NOW=true /usr/lib/kf5/start_kdeinit_wrapper --kded +kcminit_startup
#if test $? -ne 0; then
#  # Startup error
#  echo 'startkde: Could not start kdeinit5. Check your installation.'  1>&2
#  test -n "$ksplash_pid" && kill "$ksplash_pid" 2>/dev/null
#  xmessage -geometry 500x100 "Could not start kdeinit5. Check your installation."
#  exit 1
#fi

#qdbus org.kde.KSplash /KSplash org.kde.KSplash.setStage kinit &
